# Generated by Django 3.1.7 on 2021-03-27 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 27, 18, 7, 0, 659101)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
