# Generated by Django 3.1.7 on 2021-03-27 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210327_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='blogtitle',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 27, 18, 16, 2, 525888)),
        ),
    ]
