# Generated by Django 3.1.7 on 2021-03-27 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210327_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blogtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 27, 18, 20, 45, 97913)),
        ),
    ]
