# Generated by Django 3.1.7 on 2021-03-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210327_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
    ]
