# Generated by Django 3.1.7 on 2021-03-27 13:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=48)),
                ('subtitle', models.CharField(max_length=48)),
                ('body', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 27, 18, 49, 6, 630587))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
