# Generated by Django 3.1.7 on 2021-03-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210328_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='heading',
        ),
        migrations.RemoveField(
            model_name='que',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='subheading',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='que',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
