# Generated by Django 3.1.7 on 2021-03-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210328_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subheading',
            field=models.TextField(null=True),
        ),
    ]
