# Generated by Django 3.1.7 on 2021-03-28 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210328_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='assarticle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article'),
        ),
    ]
